#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
#to install numpy -
# 1. by running the following command in the terminal- pip install numpy
# OR
# 2. go to jupiter notebook and run the following command
!pip install numpy

In [ ]:
#1. for using numpy we need to import it : 
import numpy as np
#np is an allice for numpy

## 2. for create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
#to check the datatype of arr1 (it will show that it is a ndarray i.e. n dimensional array)
print(type(arr1))

#to see the shape of the array (it will show that it is a 1D array)
print(arr1.shape)

#Note -  1d array has 1 brace i.e. []
#e,g , [1 2 3 4 5]

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
##  now ,
# arr2 is our 1d array
arr2=np.array([1,2,3,4,5])
#reashaping arr2 to 2d array with 2 rows and 3 columns 
arr2.reshape(1,5)  ##now it has - 1 row and 5 columns

#note - a 2d aaray has 2 braces i.e . [[1, 2, 3, 4, 5]]

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [12]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
#now : creating arrays using some inbuild functions
np.arange(0,10,2).reshape(5,1)
#note : np.arrange(0,10 ,2) generates an array from 0 to 10 with a step of 2
#and then it is reshaped to (5,1) using reshape() function

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
#np.ones((3,4)) is an inbuild function in numpy that creates a 2D array of ones.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## to create a identity matrix : 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array : 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [ ]:
### Numpy Vectorized Operation:

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition: (elements with same index will get added)
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# now : 
## Universal Function - function that applies to the entire array
arr=np.array([2,3,4,5,6])

## square root:
print(np.sqrt(arr))

## Exponential:
print(np.exp(arr))

## Sine:
print(np.sin(arr))

## natural log: 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## now lets perform array slicing and Indexing : 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

#now :
print(arr[1:,1:3])
#here arr[] is used to access the elements of the array. The first index is the row index and the second index is the column index.
#  The : symbol is used to specify the range of rows and columns to be accessed. The , symbol is used to separate the row and column indices.
#  The first index is the row index and the second index is the column index. The indexing always starts with 0.


[[ 6  7]
 [10 11]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [36]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
# now  : 
### lets : statistical concepts--Normalization

##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [48]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])